services:
  multitenancy:
    container_name: 'multitenancy'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - multitenancy-proxy
    healthcheck:
      test: ["CMD", "php", "-r", "file_exists('/var/www/repository/artisan') || exit(1);"]
      interval: 1m
      timeout: 10s
      retries: 3

  webserver:
    container_name: 'nginx'
    image: nginx:alpine
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - multitenancy
    networks:
      - multitenancy-proxy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3

  db:
    container_name: 'db'
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    networks:
      - multitenancy-proxy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  multitenancy-proxy:
    name: "multitenancy-proxy"
    driver: bridge